#networks:
#  - inception

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    volumes:
      - ./webroot:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - wordpress
#    networks:
#      - inception
    restart: always
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - ./webroot:/var/www/html
    depends_on:
      - mariadb
#    networks:
#      - inception
    restart: always
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - ./database:/var/lib/mysql
#    networks:
#      - inception
    restart: always