services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    volumes:
      - ./webroot:/var/www/html
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: always
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    volumes:
      - ./webroot:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    restart: always
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./database
  webroot:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./webroot

networks:
  inception:
    driver: bridge
