services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    volumes:
      - ./webroot:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - wordpress
    restart: always
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - ./webroot:/var/www/html
    restart: always