FROM debian:latest

RUN apt-get update && apt-get upgrade && \
    apt-get install -y nginx openssl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY conf/nginx.conf /etc/nginx/nginx.conf

# COPY ./tools/entrypoint.sh /usr/local/bin/entrypoint.sh

# RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]